version: '3'
services:
  terraform:
    container_name: terraform
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env
    volumes:
      - .:/terraform
    working_dir: /terraform
